# file: roles/aws.infra.ansible/tasks/aws_infra_destroy.yml
---
#####################################################
# Filter
#####################################################

# AWS EC2
- name: Filter For EC2 Instances By Tags
  ec2_remote_facts:
    region: "{{ region }}"
    filters:
      "tag:DeleteTag": "{{ workshop_prefix }}-{{ owner_email }}"
  register: aws_ec2_facts
  tags: 
    - vpc_destroy

- set_fact:
    ec2_instance_ids: "{{ aws_ec2_facts|json_query('instances[*].id') }}"
  tags: 
    - vpc_destroy

# AWS VPCs
- name: Filter VPC Facts
  ec2_vpc_net_facts:
    region: "{{ region }}"
    filters:
      "tag:DeleteTag": "{{ workshop_prefix }}-{{ owner_email }}"
  register: aws_vpc_facts 
  tags: 
    - vpc_destroy

- set_fact:
    vpc_delete: "{{ aws_vpc_facts|json_query('vpcs[*].id') }}"
  tags: 
    - vpc_destroy

- set_fact:
    vpc_delete_id: "{{ vpc_delete[0] }}"
  tags: 
    - vpc_destroy

# AWS Security Group
- name: Filter Security Group Facts
  ec2_group_facts:
    region:   "{{ region }}"
    filters:
      vpc-id: "{{ vpc_delete_id }}"
  register: aws_sec_group
  tags: 
    - vpc_destroy

# AWS NACL
- name: Filter NACL Facts
  register: all_nacls
  ec2_vpc_nacl_facts:
    region:   "{{ region }}"
    filters:
      vpc-id: "{{ vpc_delete_id }}"
  tags: 
    - vpc_destroy

#####################################################
# DEBUG
#####################################################

# - name: debug subnet facts
#   debug: var=aws_subnet_facts
#   tags: 
#     - vpc_destroy

# - name: debug route facts
#   debug: var=aws_route_tables
#   tags: 
#     - vpc_destroy

# - name: debug route facts
#   debug: var=aws_route_tables|json_query('route_tables[*].associations[*].route_table_id')
#   tags: 
#     - vpc_destroy


# - name: debug sec group facts
#   debug: var=aws_sec_group.security_groups[0].group_id
#   tags: 
#     - vpc_destroy

# - name: debug nacls
#   debug: var=all_nacls.nacls[0].nacl_id
#   tags: 
#     - vpc_destroy

#####################################################
# DELETE 
#####################################################
- name: Terminate EC2 instances that were previously launched
  ec2:
    state: 'absent'
    region: "{{ region }}"
    instance_ids: "{{ ec2_instance_ids }}"
  tags: 
    - vpc_destroy

- name: Pause for EC2 instance to delete
  pause:
    seconds: "60"

- name: Delete NACL
  ec2_vpc_nacl:
    name:    "{{ nacl_name }}"
    region:  "{{ region }}"
    vpc_id:  "{{ vpc_delete_id }}"
    state:   absent
  retries: 5
  delay: 10
  tags: 
    - vpc_destroy

- name: Delete IGW
  ec2_vpc_igw:
    region:  "{{ region }}"
    vpc_id:  "{{ vpc_delete_id }}"
    state:   absent
  retries: 5
  delay: 10
  tags: 
    - vpc_destroy  

- name: Delete Sec Group
  ec2_group:
    name:     "{{ sg_name }}"
    region:   "{{ region }}"
    vpc_id:   "{{ vpc_delete_id }}"
    group_id: "{{ aws_sec_group.security_groups[0].group_id }}"
    state: absent
  retries: 5
  delay: 10
  tags: 
    - vpc_destroy

- name: Delete VPC
  ec2_vpc:
    region:        "{{ region }}"
    vpc_id:        "{{ vpc_delete_id }}"
    resource_tags: "{}"
    state:         absent
  retries: 5
  delay: 10
  tags: 
    - vpc_destroy

